version: '3.8'

services:
  orderservice:
    build:
      context: ./orderservice
      args:
        PORT: 3000
    container_name: orderservice
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_DB_URL=mongodb://mongodb:27017/orders
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=iosysmarketplace
    depends_on:
      - mongodb
      - redis

  productservice:
    build:
      context: ./productservice
      args:
        PORT: 3001
    container_name: productservice
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_DB_URL=mongodb://mongodb:27017/products
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=iosysmarketplace
    depends_on:
      - mongodb
      - redis

  userservice:
    build:
      context: ./userservice
      args:
        PORT: 3002
    container_name: userservice
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_DB_URL=mongodb://mongodb:27017/users
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=iosysmarketplace
    depends_on:
      - mongodb
      - redis

  apigateway:
    build:
      context: ./apigateway
    container_name: apigateway
    ports:
      - "8085:8085"
    environment:
      - JWT_SECRET=iosysmarketplace
    depends_on:
      - orderservice
      - productservice
      - userservice

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
